### ISSUE TITLE
Reasoning behind relative_to_margin rule

### ISSUE THREAD

**Issue by ManWithBear** [IBDecodable/IBLinter#49]
Can you please describe why you created such rule and what's wrong with that? `relative_to_margin`

**Comment by kateinoigakukun** [comment]
I created `relative_to_margin` rule to force not to use `Relative to margin` in interface builder.
`Relative to margin` option is only used in IB and this occurs discrepancies between the specified number and displayed margin.

<img width="750" alt="2018-05-25 19 40 54" src="https://user-images.githubusercontent.com/11702759/40540589-a049727e-6053-11e8-914c-6027fe0303b3.png">

**Comment by ManWithBear** [comment]
Actually it's bad practise, since by using [layoutMargins](https://developer.apple.com/documentation/uikit/uiview/1622566-layoutmargins) and `relative to margins` you have better flexibility and control over margins in app.

**Comment by kateinoigakukun** [comment]
I understand what you mean, but in my dev team case we take it seriously to avoid discrepancies between the specified number and displayed margin. 
I made this as rule non-default rule because I know it's not common. I'm planning to implement plugin function and move `relative_to_margin` to external plugin.
